In [1]:
import numpy as np

print(np.__version__)
np.show_config()

1.16.2
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Software/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Software/Anaconda\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Software/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Softwa

In [2]:
Z=np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize)) 

800 bytes


In [4]:
np.info(numpy.add)

NameError: name 'numpy' is not defined

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [6]:
Z=np.zeros(10)
Z[4]=1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
Z=np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
Z=np.zeros(50)
Z=Z[::-1]
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [9]:
Z=np.arange(50)
Z=Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [10]:
Z=np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
nz = np.nonzero[1,2,0,0,4,0]
print(nz)

TypeError: 'function' object is not subscriptable

In [12]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [13]:
Z=np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
Z=np.random.random(3,3,3)
print(Z)

TypeError: random_sample() takes at most 1 positional argument (3 given)

In [15]:
Z=np.random.random((3,3,3))
print(Z)

[[[0.55390524 0.51263164 0.87975789]
  [0.19460125 0.55910226 0.30345027]
  [0.53112104 0.41313992 0.31209734]]

 [[0.93163924 0.96736975 0.62925415]
  [0.55213065 0.73507    0.88847407]
  [0.60750052 0.12451621 0.68647492]]

 [[0.75462841 0.79342775 0.91580771]
  [0.47173264 0.6337925  0.12005794]
  [0.30400241 0.88979534 0.72241344]]]


In [16]:
Z=np.random.random((10,10))
Zmin,Zmax=Z.min(),Z.max()
print(Zmin,Zmax)

0.0017864196505491536 0.9883406979233513


In [17]:
Z=np.random.random(30)
Zavg=Z.mean()
print(Zavg)

0.48065656350978614


In [18]:
Z=np.ones((10,10))
Z[1:-1,1:-1]=0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [19]:
Z=np.ones((5,5))
Z=np.pad(Z,pad_width=1,mod='constant',constant_values=0)
print(Z)


TypeError: pad() missing 1 required positional argument: 'mode'

In [20]:
Z=np.ones((5,5))
Z=np.pad(Z,pad_width=1,mode='constant',constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [21]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3 == 3*0.1)

nan
False
False
nan
False


In [22]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [23]:
Z = np.diag(1+np.arange(4),k=1)
print(Z)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [24]:
Z=np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [25]:
Z=np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
print(Z)

[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]


In [26]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [1]:
Z = np.tail(np.array([[0,1][1,0]]),(4,4))

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
Z = np.tail(np.array([[0,1][1,0]]),(4,4))

AttributeError: module 'numpy' has no attribute 'tail'

In [4]:
Z = np.tile(np.array([[0,1][1,0]]),(4,4))

TypeError: list indices must be integers or slices, not tuple

In [5]:
Z = np.tail(np.array([[0,1],[1,0]]),(4,4))
print(Z)

AttributeError: module 'numpy' has no attribute 'tail'

In [6]:
Z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [7]:
Z= np.random.random(5,5)
Zmax,Zmin=Z.max(),Z.min()
Z=(Z-Zmin)/(Z-Zmax)
print(Z)

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [8]:
Z= np.random.random((5,5))
Zmax,Zmin=Z.max(),Z.min()
Z=(Z-Zmin)/(Z-Zmax)
print(Z)

[[-1.05618414e+00 -4.34965020e-02 -4.57475029e+00 -5.61328274e+00
  -1.81770058e+00]
 [-8.47703996e-02 -1.72534755e+00 -1.50950097e+01 -2.66765061e-01
              inf]
 [-2.26407142e+01 -4.62746301e+00 -4.17419215e-01 -2.45123664e-02
  -8.01293737e-01]
 [-2.48603691e+00 -1.12518416e+00 -2.02252839e+00 -8.08761408e+00
  -3.38197645e-02]
 [-0.00000000e+00 -5.64926992e-04 -1.65798325e+00 -1.71319712e+00
  -2.01068507e-01]]


D:\Software\Anaconda\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [9]:
color = np.dtype([("r",np.ubyte,1),
                  ("g",np.ubyte,1),
                  ("b",np,ubyte,1)])
color

NameError: name 'ubyte' is not defined

In [10]:
color = np.dtype([("r",np.ubyte,1),
                  ("g",np.ubyte,1),
                  ("b",np,ubyte,1),
                  ("a",np.ubyte,1)])
color

NameError: name 'ubyte' is not defined

In [11]:
color = np.dtype([("r",np.ubyte,1),
                  ("g",np.ubyte,1),
                  ("b",np.ubyte,1),
                  ("a",np.ubyte,1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [12]:
Z=np.dot(np.ones(5,3),np.ones(3,2))
print(Z)

TypeError: data type not understood

In [13]:
Z=np.dot(np.ones((5,3)),np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [14]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [15]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [16]:
z = np.arange(5)
z**z

array([  1,   1,   4,  27, 256], dtype=int32)

In [17]:
z = np.arange(5)
2 << z >> 2

array([0, 1, 2, 4, 8], dtype=int32)

In [18]:
1j*z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [19]:
z < -z

array([False, False, False, False, False])

In [20]:
z/1/1

array([0., 1., 2., 3., 4.])

In [21]:
z<z>z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [22]:
np.array(0)/np.array(0)

D:\Software\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [23]:
np.array(0)//np.array(0)

D:\Software\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [24]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

In [25]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 4. -7. -4.  3. -7.  5.  6.  5. -6.  1.]


In [26]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 3 4 5 8]


In [27]:
np.sqrt(-1) == np.emath.sqrt(-1)

D:\Software\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [28]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-06-22
Today is 2019-06-23
Tomorrow is 2019-06-24


In [29]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']
