In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
values = pd.Series(['apple','orange','apple','apple']*2)

In [4]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [5]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [6]:
pd.value_counts(values)

apple     6
orange    2
dtype: int64

In [7]:
values = pd.Series([0,1,0,0]*2)

In [8]:
dim = pd.Series(['apple','orange'])

In [9]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [10]:
dim

0     apple
1    orange
dtype: object

In [11]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [12]:
fruits = ['apple','orange','apple','apple']*2

In [13]:
N = len(fruits)

In [14]:
df = pd.DataFrame({'fruit':fruits,
                  'basket_id':np.arange(N),
                  'count':np.random.randint(3,15,size=N),
                  'weight':np.random.uniform(0,4,size=N)},
                 columns=['basket_id','fruit','count','weight'])

In [15]:
df

basket_id   fruit  count    weight
0          0   apple     11  1.002045
1          1  orange     13  1.408978
2          2   apple      6  0.387467
3          3   apple     13  3.446898
4          4   apple     12  1.895542
5          5  orange     12  1.930328
6          6   apple      8  3.941875
7          7   apple     11  0.745974

In [16]:
fruit_cat = df['fruit'].astype('category')

In [17]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): [apple, orange]

In [18]:
c = fruit_cat.values

In [19]:
type(c)

pandas.core.arrays.categorical.Categorical

In [20]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [21]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [22]:
df['fruit'] = df['fruit'].astype('category')

In [23]:
df.fruit

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): [apple, orange]

In [24]:
my_categories = pd.Categorical(['foo','bar','baz','foo','bar'])

In [25]:
my_categories

[foo, bar, baz, foo, bar]
Categories (3, object): [bar, baz, foo]

In [26]:
ordered_cat = pd.Categorical.from_codes(codes,categories,ordered=True)

NameError: name 'codes' is not defined

In [27]:
codes = [0,1,2,0,0,1]

In [28]:
ordered_cat = pd.Categorical.from_codes(codes,categories,ordered=True)

NameError: name 'categories' is not defined

In [29]:
categories = ['foo','bar','baz']

In [30]:
ordered_cat = pd.Categorical.from_codes(codes,categories,ordered=True)

In [31]:
ordered_cat

[foo, bar, baz, foo, foo, bar]
Categories (3, object): [foo < bar < baz]

In [32]:
np.random.seed(12345)

In [33]:
draws = np.random.randn(1000)

In [34]:
draws[:5]

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057])

In [35]:
array([-0.2047,0.4789,-0.5194,-0.5557,1.9658])

NameError: name 'array' is not defined

In [36]:
bins = pd.qcut(draws,4)

In [37]:
bins

[(-0.684, -0.0101], (-0.0101, 0.63], (-0.684, -0.0101], (-0.684, -0.0101], (0.63, 3.928], ..., (-0.0101, 0.63], (-0.684, -0.0101], (-2.9499999999999997, -0.684], (-0.0101, 0.63], (0.63, 3.928]]
Length: 1000
Categories (4, interval[float64]): [(-2.9499999999999997, -0.684] < (-0.684, -0.0101] < (-0.0101, 0.63] < (0.63, 3.928]]

In [38]:
bins = pd.qcut(draws,4,labels=['Q1','Q2','Q3','Q4'])

In [39]:
bins

[Q2, Q3, Q2, Q2, Q4, ..., Q3, Q2, Q1, Q3, Q4]
Length: 1000
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [40]:
bins = pd.Series(bins,name='quartile')

In [41]:
results = (pd.Series(draws).groupby(bins).agg(['count','min','max']).reset_index())

In [42]:
results

quartile  count       min       max
0       Q1    250 -2.949343 -0.685484
1       Q2    250 -0.683066 -0.010115
2       Q3    250 -0.010032  0.628894
3       Q4    250  0.634238  3.927528

In [43]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [44]:
N = 10000000

In [45]:
draws = pd.Series(np.random.randn(N))

In [46]:
labels = pd.Series(['foo','bar','baz','qux']*(N//4))

In [47]:
categories = labels.astype('category')

In [48]:
labels.memory_usage()

80000080

In [49]:
categories.memory_usage()

10000272

In [50]:
%time _ = labels.astypey('category')

AttributeError: 'Series' object has no attribute 'astypey'

In [51]:
%time _ = labels.astype('category')

Wall time: 399 ms


In [52]:
s = pd.Series(['a','b','c','d']*2)

In [53]:
cat_s = s.astype('category')

In [54]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): [a, b, c, d]

In [55]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [56]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [57]:
actual_categories = ['a','b','c','d','e']

In [58]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [59]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): [a, b, c, d, e]

In [60]:
cat_s.value_counts()

d    2
c    2
b    2
a    2
dtype: int64

In [61]:
cat_s2.value_counts()

d    2
c    2
b    2
a    2
e    0
dtype: int64

In [62]:
cat_s3 = cat_s[cat_s.isin(['a','b'])]

In [63]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): [a, b, c, d]

In [64]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): [a, b]

In [65]:
df = pd.DataFrame({'key':['a','b','c']*4,
                  'value':np.arange(12.)})

In [66]:
df

key  value
0    a    0.0
1    b    1.0
2    c    2.0
3    a    3.0
4    b    4.0
5    c    5.0
6    a    6.0
7    b    7.0
8    c    8.0
9    a    9.0
10   b   10.0
11   c   11.0

In [67]:
g = df.groupby('key').value

In [68]:
g.mean()

key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [69]:
g.transform(lambda x:x.mean())

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [70]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [71]:
g.transform(lambda x:x*2)

0      0.0
1      2.0
2      4.0
3      6.0
4      8.0
5     10.0
6     12.0
7     14.0
8     16.0
9     18.0
10    20.0
11    22.0
Name: value, dtype: float64

In [72]:
g.transform(lambda x:x.rank(ascending=False))

0     4.0
1     4.0
2     4.0
3     3.0
4     3.0
5     3.0
6     2.0
7     2.0
8     2.0
9     1.0
10    1.0
11    1.0
Name: value, dtype: float64

In [73]:
g.transform(normalize)

NameError: name 'normalize' is not defined

In [74]:
def normalize(x):
    return (x-x.mean())/x.std()

In [75]:
g.transform(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [76]:
a.apply(normalize)

NameError: name 'a' is not defined

In [77]:
g.apply(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [78]:
normalized = (df['value']-g.transform('mean'))/g.transform('std')

In [79]:
normalized

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [80]:
N = 15

In [81]:
times = pd.date_range('2017-05-20 00:00',freq='lmin',periods=N)

ValueError: Invalid frequency: lmin

In [82]:
times = pd.date_range('2017-05-20 00:00',freq='1min',periods=N)

In [83]:
df = pd.DataFrame({'time':times,
                 'value':np.arange(N)})

In [84]:
df

time  value
0  2017-05-20 00:00:00      0
1  2017-05-20 00:01:00      1
2  2017-05-20 00:02:00      2
3  2017-05-20 00:03:00      3
4  2017-05-20 00:04:00      4
5  2017-05-20 00:05:00      5
6  2017-05-20 00:06:00      6
7  2017-05-20 00:07:00      7
8  2017-05-20 00:08:00      8
9  2017-05-20 00:09:00      9
10 2017-05-20 00:10:00     10
11 2017-05-20 00:11:00     11
12 2017-05-20 00:12:00     12
13 2017-05-20 00:13:00     13
14 2017-05-20 00:14:00     14

In [85]:
df.set_index('time').resample('5min').count()

value
time                      
2017-05-20 00:00:00      5
2017-05-20 00:05:00      5
2017-05-20 00:10:00      5

In [86]:
df2 = pd.DataFrame({'time':times.repeat(3),
                    'key':np.tile(['a','b','c'],N),
                    'value':np.arange(N*3.)})

In [87]:
df2[:7]

time key  value
0 2017-05-20 00:00:00   a    0.0
1 2017-05-20 00:00:00   b    1.0
2 2017-05-20 00:00:00   c    2.0
3 2017-05-20 00:01:00   a    3.0
4 2017-05-20 00:01:00   b    4.0
5 2017-05-20 00:01:00   c    5.0
6 2017-05-20 00:02:00   a    6.0

In [88]:
time_key = pd.TimeGrouper('5min')

D:\Software\Anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: pd.TimeGrouper is deprecated and will be removed; Please use pd.Grouper(freq=...)
  """Entry point for launching an IPython kernel.


In [89]:
resampled = (df2.set_index('time').groupby(['key',time_key]).sum())

In [90]:
resampled

value
key time                      
a   2017-05-20 00:00:00   30.0
    2017-05-20 00:05:00  105.0
    2017-05-20 00:10:00  180.0
b   2017-05-20 00:00:00   35.0
    2017-05-20 00:05:00  110.0
    2017-05-20 00:10:00  185.0
c   2017-05-20 00:00:00   40.0
    2017-05-20 00:05:00  115.0
    2017-05-20 00:10:00  190.0

In [91]:
resampled.reset_index()

key                time  value
0   a 2017-05-20 00:00:00   30.0
1   a 2017-05-20 00:05:00  105.0
2   a 2017-05-20 00:10:00  180.0
3   b 2017-05-20 00:00:00   35.0
4   b 2017-05-20 00:05:00  110.0
5   b 2017-05-20 00:10:00  185.0
6   c 2017-05-20 00:00:00   40.0
7   c 2017-05-20 00:05:00  115.0
8   c 2017-05-20 00:10:00  190.0

In [92]:
df = load_data()

NameError: name 'load_data' is not defined