In [1]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)

array([3., 3., 3.])

In [4]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [5]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [6]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [7]:
Z = np.random.uniform(0,10,10)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[4. 5. 0. 6. 0. 5. 7. 5. 1. 5.]
[4. 5. 0. 6. 0. 5. 7. 5. 1. 5.]
[4. 5. 0. 6. 0. 5. 7. 5. 1. 5.]
[4 5 0 6 0 5 7 5 1 5]
[4. 5. 0. 6. 0. 5. 7. 5. 1. 5.]


In [8]:
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [9]:
In [ ]:
def generate():
     for x in range(10):
         yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

SyntaxError: invalid syntax (<ipython-input-9-3cacad1fcbd8>, line 1)

In [10]:
def generate():
     for x in range(10):
         yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [11]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [12]:
Z = np.random.random(10)
Z.sort()
print (Z)

[0.01817357 0.01999084 0.06192124 0.08460298 0.2979087  0.39551181
 0.56724466 0.62264054 0.86310832 0.91860071]


In [13]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [14]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [15]:
z = np.zeros(10)
z.flags.writeable = False
z[0]=1

ValueError: assignment destination is read-only

In [16]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[0.27420805 0.41873169 1.03873445 0.7137604  0.82327618 1.00392678
 0.61402051 1.08786966 1.1976807  0.39252122]
[0.30403686 1.16538843 0.73284322 1.48092718 0.30676358 0.53203731
 1.54511385 0.82950612 0.97106823 0.15157968]


In [17]:
Z = np.random.random(10)
Z[Z.argmax()] = 1
print (Z)

[1.         0.87700696 0.92422023 0.2034862  0.05742286 0.21707257
 0.16467202 0.76543826 0.17942854 0.13002112]


In [18]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                              np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [19]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [20]:
for dtype in [np.int8, np.int32, np.int64]:
     print(np.iinfo(dtype).min)
     print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
     print(np.finfo(dtype).min)
     print(np.finfo(dtype).max)
     print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [21]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print (Z)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

In [22]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

7


In [23]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print (Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [25]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print (D)

[[0.         0.3511703  0.70110211 0.68702253 0.26730054 0.22752637
  0.50715155 0.81665933 0.41714764 0.56401786]
 [0.3511703  0.         0.6284602  0.65911947 0.6184197  0.46565359
  0.3499083  0.92268302 0.38699828 0.41857823]
 [0.70110211 0.6284602  0.         0.08647572 0.85966581 0.55225524
  0.28304808 0.44066106 0.28611461 0.21978898]
 [0.68702253 0.65911947 0.08647572 0.         0.82149542 0.51622631
  0.3287364  0.35620446 0.28796318 0.27463968]
 [0.26730054 0.6184197  0.85966581 0.82149542 0.         0.30741089
  0.72793188 0.83854919 0.60228455 0.77326484]
 [0.22752637 0.46565359 0.55225524 0.51622631 0.30741089 0.
  0.44623039 0.59302799 0.30407531 0.48113547]
 [0.50715155 0.3499083  0.28304808 0.3287364  0.72793188 0.44623039
  0.         0.64839581 0.15773613 0.06909879]
 [0.81665933 0.92268302 0.44066106 0.35620446 0.83854919 0.59302799
  0.64839581 0.         0.54059286 0.6105073 ]
 [0.41714764 0.38699828 0.28611461 0.28796318 0.60228455 0.30407531
  0.15773613 0.54059

In [26]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [27]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print (index, value)
for index in np.ndindex(Z.shape):
    print (index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [28]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [29]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [30]:
X = np.random.rand(5, 10)
# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.08058919  0.28690116 -0.10146016 -0.3963306   0.43415676  0.11012696
  -0.33371355  0.26548665 -0.20189052 -0.14386589]
 [-0.43423511  0.08041123  0.15414326 -0.27511218 -0.24670253 -0.07376864
   0.27486788  0.44221885  0.17446985 -0.09629261]
 [-0.32776153 -0.19829801 -0.2401529   0.23574256  0.00713569 -0.02043096
  -0.36057367  0.34132972  0.52812117  0.03488793]
 [ 0.04674799  0.25162304  0.20158052  0.42436259  0.00805205 -0.33989459
  -0.39102578 -0.36764682  0.47920009 -0.31299908]
 [-0.06079026  0.32714803  0.34918537 -0.33287896  0.18041957 -0.27799683
   0.11177857 -0.15018753 -0.13492719 -0.01175076]]


In [31]:
Z = np.random.randint(0,10,(3,3))
print (Z)
print (Z[Z[:,1].argsort()])

[[0 3 5]
 [9 3 5]
 [0 3 7]]
[[0 3 5]
 [9 3 5]
 [0 3 7]]


In [32]:
Z = np.random.randint(0,3,(3,10))
print ((~Z.any(axis=0)).any())

True


In [33]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print (m)

0.6016870700039687


In [34]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [35]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [36]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 3. 1. 4. 5. 2. 2. 3. 3. 4.]


In [37]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [38]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)

8


In [39]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print (sum)

[[62 69 62 69]
 [47 40 59 51]
 [50 62 61 62]]


In [40]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print (D_means)

import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.49797182 0.46066237 0.54943113 0.33580441 0.45775121 0.53242502
 0.54951852 0.52970846 0.46999011 0.40970151]
0    0.497972
1    0.460662
2    0.549431
3    0.335804
4    0.457751
5    0.532425
6    0.549519
7    0.529708
8    0.469990
9    0.409702
dtype: float64


In [41]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
# slow version
np.diag(np.dot(A, B))

array([0.50492056, 1.32780055, 0.8510553 , 0.66463184, 1.10591679])

In [42]:
print(A)
print(B)

[[0.44022306 0.92329502 0.13899124 0.6896316  0.42668641]
 [0.24785774 0.43732403 0.43303534 0.55860681 0.89945694]
 [0.18999166 0.99668398 0.41011389 0.01279101 0.840017  ]
 [0.759593   0.27703629 0.45071591 0.9214528  0.56657138]
 [0.58084484 0.51966337 0.71783969 0.9412602  0.37919558]]
[[0.08346836 0.18091914 0.82242438 0.40970974 0.15420074]
 [0.25422106 0.41843428 0.18259029 0.02519519 0.31864137]
 [0.003318   0.59002355 0.34224661 0.04693836 0.00792035]
 [0.05144064 0.30401229 0.09842159 0.18019108 0.70571591]
 [0.4629127  0.75005546 0.44189309 0.28106919 0.476841  ]]


In [43]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print (Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [44]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A*B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [45]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print (A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [46]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print (G)

[( 4, 83) ( 4, 93) ( 6, 10) ( 6, 91) (10, 37) (10, 65) (10, 91) (16, 76)
 (16, 94) (29, 85) (29, 87) (30, 67) (30, 89) (37, 65) (38, 86) (38, 95)
 (50, 59) (50, 68) (50, 93) (50, 94) (50, 95) (59, 94) (67, 89) (68, 95)
 (76, 94) (83, 93) (85, 87) (86, 95) (93, 95)]


In [47]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print (A)

[1 1 2 3 4 4 6]


In [48]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)

print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [49]:
Z = np.random.randint(0,2,100)
print(Z)
np.logical_not(Z, out=Z)

[0 1 1 0 1 0 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 0 1 0 1 0 1 1 1 0 0 1 1 1 1 0 0
 0 0 1 0 0 1 0 1 1 1 1 0 1 1 0 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 1 0 1 0 0 0 0
 1 0 1 0 1 1 0 0 0 0 1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 1]


array([1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0])

In [51]:
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.41691391, -0.83055313, -0.48953497,  0.16694047,  0.78033781,
       -0.39112877,  0.4468898 , -0.05315555, -0.54663319, -0.49554566,
       -0.96269357, -0.68943119, -0.4050608 , -0.20930738,  0.17521888,
        0.31480214,  0.69874176,  0.69117731, -0.58496843,  0.27785818,
       -0.80049658, -0.7187365 , -0.14440299, -0.95490281, -0.89810574,
        0.71661256, -0.83362567, -0.89648394, -0.63859862, -0.52956274,
       -0.00710374, -0.9280039 , -0.32206184,  0.89090012,  0.79999312,
       -0.56999803, -0.84456291, -0.91899787,  0.91712261, -0.63727428,
        0.05668188, -0.63721912,  0.15904563,  0.28615217,  0.82872194,
        0.57523804, -0.78236515,  0.47283835, -0.450328  , -0.45380723,
       -0.99901869, -0.07293619,  0.1587206 , -0.16914321,  0.38707837,
        0.66546397, -0.36451811, -0.4600938 ,  0.68241181,  0.22286383,
       -0.174562  , -0.38959245,  0.89215456,  0.47543959,  0.21478379,
        0.69034985, -0.06069406, -0.38499372,  0.31251746,  0.36

In [52]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

print (distance(P0, P1, p))

[ 3.10342611 11.98376733  5.83268592  4.90669001  0.15337867  8.28060756
  1.29705479  0.56197278 11.65966201  2.70237811]


In [53]:
P0 = np.random.uniform(-10, 10, (10,2))

In [54]:
print(P0)

[[ 9.46304222 -3.87405599]
 [ 3.79286896 -7.83556855]
 [-9.94993014  5.73421116]
 [ 4.40607246  4.00547292]
 [ 6.50420352  1.659484  ]
 [ 7.05889118 -3.45332139]
 [ 8.61745629 -5.58701099]
 [ 6.21131775 -6.53019792]
 [-8.03958735 -3.27289329]
 [-1.23339639 -4.87072017]]


In [55]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 4.89007852  4.5975246   0.94932383  5.24161709  3.75994005  1.31176207
   3.03401176  3.64039616  4.21302566  1.90520822]
 [ 1.11518028  8.99069711  8.46339181  4.01246352  0.26822637  5.34743647
   0.70077682  5.73975678  4.79080734  7.03821492]
 [ 3.0149437  12.64434143  3.22308058  2.75842649  8.87516166  3.56252482
   4.7596282   0.87616288  1.56672545  3.99121588]
 [ 5.47807719  1.66639851  7.20778894  4.56647394  6.62686207 10.20664594
   8.47934915  4.09235153  1.61382301  3.71081332]
 [13.68090872  4.4146627   5.35813231  7.73028701  2.20162165  1.50106609
  11.83379776  8.44280928 10.46964086  8.29708852]
 [ 4.79160889 13.44098594  7.83407998  2.13461803  5.68400667  0.85574963
   4.40051939  5.39152419  5.57995948  7.94297888]
 [ 3.04643714  7.265879    2.84995169  8.05388447  8.3489281   5.68905135
   0.43497297  5.32542369  4.98850119  2.58486655]
 [ 7.18022966 15.35786629 10.96282534  5.08944201  5.02217426  2.67976666
   5.68208904  8.5362901   8.70668959 11.06036788]


In [56]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print (rank)

10


In [57]:
Z = np.random.uniform(0,1,(10,10))
print(Z)

[[0.17460959 0.48814362 0.33917648 0.34265851 0.53314026 0.17017645
  0.07547554 0.59895217 0.52707952 0.90464337]
 [0.55406595 0.51659629 0.71718565 0.23278073 0.74793692 0.78613791
  0.90655302 0.21189695 0.87824494 0.73690018]
 [0.85930009 0.00723511 0.90506181 0.15516962 0.15609312 0.50664464
  0.80271114 0.39449034 0.06050925 0.29572326]
 [0.33769782 0.41945638 0.50346844 0.34520981 0.60208996 0.85578268
  0.61244049 0.49945444 0.84544665 0.64780838]
 [0.78068914 0.76705891 0.62298124 0.97103622 0.75287289 0.72498087
  0.78410357 0.02542631 0.01921376 0.80658103]
 [0.18775374 0.30704468 0.9346358  0.82780184 0.27633525 0.89979848
  0.80187532 0.96039482 0.54488263 0.84881072]
 [0.26046162 0.71846669 0.71127791 0.85196028 0.31686584 0.30270302
  0.76452226 0.3089618  0.58590714 0.46726722]
 [0.82510068 0.94232604 0.50320238 0.43658077 0.63236784 0.02200351
  0.17572874 0.10073684 0.86058962 0.03576406]
 [0.65690011 0.65349008 0.78623839 0.4739884  0.29980803 0.06999177
  0.72964304