In [3]:
#这里的题跟着答案敲一遍吧。有个印象。从70题之后，就已经看不懂了。
import numpy as np
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

1


In [4]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

NameError: name 'stride_tricks' is not defined

In [5]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

AttributeError: module 'numpy' has no attribute 'stride_tricks'

In [6]:
from np import * 
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

ModuleNotFoundError: No module named 'np'

In [7]:
from numpy import * 
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

NameError: name 'stride_tricks' is not defined

In [8]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

[[[[2 4 3]
   [3 2 3]
   [4 1 1]]

  [[4 3 1]
   [2 3 4]
   [1 1 1]]

  [[3 1 3]
   [3 4 4]
   [1 1 4]]

  [[1 3 1]
   [4 4 4]
   [1 4 1]]

  [[3 1 3]
   [4 4 0]
   [4 1 0]]

  [[1 3 0]
   [4 0 3]
   [1 0 4]]

  [[3 0 1]
   [0 3 2]
   [0 4 4]]

  [[0 1 2]
   [3 2 3]
   [4 4 1]]]


 [[[3 2 3]
   [4 1 1]
   [1 4 4]]

  [[2 3 4]
   [1 1 1]
   [4 4 0]]

  [[3 4 4]
   [1 1 4]
   [4 0 0]]

  [[4 4 4]
   [1 4 1]
   [0 0 3]]

  [[4 4 0]
   [4 1 0]
   [0 3 2]]

  [[4 0 3]
   [1 0 4]
   [3 2 0]]

  [[0 3 2]
   [0 4 4]
   [2 0 2]]

  [[3 2 3]
   [4 4 1]
   [0 2 0]]]


 [[[4 1 1]
   [1 4 4]
   [0 4 4]]

  [[1 1 1]
   [4 4 0]
   [4 4 2]]

  [[1 1 4]
   [4 0 0]
   [4 2 2]]

  [[1 4 1]
   [0 0 3]
   [2 2 1]]

  [[4 1 0]
   [0 3 2]
   [2 1 3]]

  [[1 0 4]
   [3 2 0]
   [1 3 2]]

  [[0 4 4]
   [2 0 2]
   [3 2 0]]

  [[4 4 1]
   [0 2 0]
   [2 0 0]]]


 [[[1 4 4]
   [0 4 4]
   [1 1 4]]

  [[4 4 0]
   [4 4 2]
   [1 4 0]]

  [[4 0 0]
   [4 2 2]
   [4 0 1]]

  [[0 0 3]
   [2 2 1]
   [0 1 3]]

  [[0 3 2]
   

In [9]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print (S)

[[ 0  8  5 10 14]
 [ 8  1 12  9 13]
 [ 5 12  8 42  6]
 [10  9 42  7 12]
 [14 13  6 12  0]]


In [10]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print (S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [11]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print (S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [12]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print (Z)

[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [13]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [14]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print (R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [15]:
x = np.random.rand()
np.power(x,3)

0.46912535096216085

In [16]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print (rows)

[0 1 2]


In [17]:
Z = np.random.randint(0,5,(10,3))
print (Z)

# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print (U)

[[3 2 2]
 [4 3 3]
 [0 0 3]
 [3 0 0]
 [2 3 1]
 [3 3 1]
 [3 2 0]
 [0 0 2]
 [0 4 2]
 [0 3 3]]
[[3 2 2]
 [4 3 3]
 [0 0 3]
 [3 0 0]
 [2 3 1]
 [3 3 1]
 [3 2 0]
 [0 0 2]
 [0 4 2]
 [0 3 3]]


In [18]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [19]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('sum')
print (np.einsum('i->', A))
np.sum(A)

sum
5.121460143288872


5.121460143288871

In [20]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [21]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print (X[M])

[[2. 0. 1. 1.]]


In [22]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print (confint)

[-0.47591408 -0.0470977 ]
