In [1]:
import pandas as pd

In [2]:
obj = pd.Series([4,7,-5,3])

In [3]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [6]:
obj.values

array([ 4,  7, -5,  3])

In [9]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [11]:
obj2 = pd.Series([4,5,7,3],index=['d','b','a','c'])

In [12]:
obj2

d    4
b    5
a    7
c    3
dtype: int64

In [13]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [14]:
obj2['a']

7

In [15]:
obj2['c','a','d']

KeyError: ('c', 'a', 'd')

In [16]:
obj2[['c','a','d']]

c    3
a    7
d    4
dtype: int64

In [17]:
obj2 * 2

d     8
b    10
a    14
c     6
dtype: int64

In [18]:
import numpy as np

In [19]:
np.exp(obj2)

d      54.598150
b     148.413159
a    1096.633158
c      20.085537
dtype: float64

In [20]:
sdata={'a':100,'b':200,'c':300,'d':400}
obj3=pd.Series(sdata)

In [21]:
obj3

a    100
b    200
c    300
d    400
dtype: int64

In [22]:
states = ['a','c','b','d']

In [23]:
obj4 = pd.Series(sdata,index=states)

In [24]:
obj4

a    100
c    300
b    200
d    400
dtype: int64

In [25]:
pd.isnull(obj4)

a    False
c    False
b    False
d    False
dtype: bool

In [26]:
obj4.name = 'population'

In [27]:
obj4.index.name = 'state'

In [28]:
obj4

state
a    100
c    300
b    200
d    400
Name: population, dtype: int64

In [29]:
obj4.index=['bob','steve','jeff','ryan']

In [30]:
obj4

bob      100
steve    300
jeff     200
ryan     400
Name: population, dtype: int64

In [31]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
        'year':[2000,2001,2002,2001,2002,2003],
        'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)

In [32]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [33]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [34]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [35]:
pd.DataFrame(data,columns=['year','state','pop'],
             index=['one','two','three','four','five','sixe'])

year   state  pop
one    2000    Ohio  1.5
two    2001    Ohio  1.7
three  2002    Ohio  3.6
four   2001  Nevada  2.4
five   2002  Nevada  2.9
sixe   2003  Nevada  3.2

In [36]:
frame2.columns

NameError: name 'frame2' is not defined

In [37]:
frame.columns

Index(['state', 'year', 'pop'], dtype='object')

In [38]:
frame['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [39]:
frame2.year

NameError: name 'frame2' is not defined

In [40]:
frame.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [41]:
frame2 = pd.DataFrame(data,columns=['year','state','pop','debt'],
             index=['one','two','three','four','five','sixe'])

In [42]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
sixe   2003  Nevada  3.2  NaN

In [43]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [44]:
frame2['debt']=16.5

In [45]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [46]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
sixe   2003  Nevada  3.2  16.5

In [47]:
frame2['debt']=np.arrange(6.)

AttributeError: module 'numpy' has no attribute 'arrange'

In [48]:
frame2['debt']=np.arange(6.)

In [49]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
sixe   2003  Nevada  3.2   5.0

In [50]:
val = pd.Series([1,2,3],index=['one','four','five'])

In [51]:
frame2['debt']=val

In [52]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   1.0
two    2001    Ohio  1.7   NaN
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4   2.0
five   2002  Nevada  2.9   3.0
sixe   2003  Nevada  3.2   NaN

In [53]:
frame2['eastern']=frame.state =='Ohio' 

In [54]:
frame2

year   state  pop  debt eastern
one    2000    Ohio  1.5   1.0     NaN
two    2001    Ohio  1.7   NaN     NaN
three  2002    Ohio  3.6   NaN     NaN
four   2001  Nevada  2.4   2.0     NaN
five   2002  Nevada  2.9   3.0     NaN
sixe   2003  Nevada  3.2   NaN     NaN

In [55]:
frame2['eastern']=frame2.state =='Ohio'

In [56]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   1.0     True
two    2001    Ohio  1.7   NaN     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4   2.0    False
five   2002  Nevada  2.9   3.0    False
sixe   2003  Nevada  3.2   NaN    False

In [57]:
del frame2['eastern']

In [58]:
drame2.columns

NameError: name 'drame2' is not defined

In [59]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [60]:
pop={'Nevada':{2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [61]:
frame3=pd.DataFrame(pop)

In [62]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [63]:
frame3.T


2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [64]:
frame3.index.name = 'year';frame.columns.name='state'

In [65]:
frame

state   state  year  pop
0        Ohio  2000  1.5
1        Ohio  2001  1.7
2        Ohio  2002  3.6
3      Nevada  2001  2.4
4      Nevada  2002  2.9
5      Nevada  2003  3.2

In [66]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [67]:
frame2.values

array([[2000, 'Ohio', 1.5, 1.0],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, 2.0],
       [2002, 'Nevada', 2.9, 3.0],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [68]:
obj = pd.Series(range(3),index=['a','b','c'])

In [69]:
index = obj.index

In [70]:
index

Index(['a', 'b', 'c'], dtype='object')

In [71]:
index[:1]

Index(['a'], dtype='object')

In [72]:
labels = pd.Index(np.arange(3))

In [73]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [74]:
obj2 = pd.Series([1.5,-2.5,0],index=labels)

In [75]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [76]:
frame3

Nevada  Ohio
year              
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [77]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object')

In [78]:
'Ohio' in frame3.columns

True

In [79]:
2003 in frame3.index

False

In [80]:
dup_labels = pd.Index(['foo','foo','bar','bar'])

In [81]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')